# NumPy Basis: Arrays and Vectorized Computation

NumPy, short for Numerical Python, is one of the most import foundational packagers for numerical computing in Python. Many computational packages providing scientific functionality use NumPy's array objects as one of the standard interface for data exchange. 

Here are some of the things you'll find in NumPy:

- ndarray, an effcient multidimensional array prociding fast raay-oriented arithmetic operations and flexible capabilites.
- Mathemcatical functions for fast operations on entire arrays of data without having to write loops.
- Tools for reading/writing array data to disk and working with memory-mapped files.
- Linear algebra, random number genrations, and fourier transform capabilities
- Fast array-based operations for data munging and cleaning, subsetting and filtering, transformation, and any other kind of computation
- Common array algorithms like sorting, unique, and set operations
- Efficient descriptive statistics and aggregating/summarizing data
- Data alignment and relational data manipulations for merging and joining heter‐
ogeneous datasets
- Expressing conditional logic as array expressions instead of loops with if-elifelse branches
-  Group-wise data manipulations (aggregation, transformation, and function
application)


One of the reasons NumPy is so important for numerical computations in Python is becuase it is designed for efficiency on large arrays of data. There are number of reasons for this. 

- NumPy internally stores data in contiguous block of memory, independent of other built-in Python objects. Numpy's library of algorithms written in C language can operate on this memory without any type checking or other overhead. NumPy arrays alos use much less memory than built-in Python sequences.
- NumPy operations perform complex computations on entire arrays without the need for Python for loops, which can be slow for large sequences. NumPy is faster than regular Python code becuase its C-based alogirthms avoid overhead present with regular interpreted Python code. 

In [18]:
### To give you an idea of performance difference, consider a NumPy array of one million integers, and equivalent Python list

import numpy as np # importing numpy library as np
my_arr = np.arange(1_000_000)

my_list = list(range(1_000_000)) # list

### now let's multiply each sequence by 2

%timeit my_arr2 = my_arr * 2


%timeit my_list2 = [x * 2 for x in my_list] 

               

2.08 ms ± 21.8 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
94.1 ms ± 3.42 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


NumPy based algorithms are generally 10 to 100 times faster than their pure Python counterparts and use significally less memory.

## NumPy ndarray: A Multidimensional Array Object.

Key features of NumPy is its N-dimensional array object, or ndarray, which is fast, flexible container for large datasets in Python. Arrays enable you to perform mathematical operations on whole blocks of data using similar syntax to the equivalant operations between scalar elements. 

In [19]:
import numpy as np

data = np.array([
    [1.5, -0.1, 3],
    [0, -3, 6.5]
])

data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [20]:
### Matematical operations 

data * 10   # all elements will multply by 10.

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [23]:
data + data  # values are added to each other.

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [25]:
from numpy import *

mydata = data
print(mydata)

[[ 1.5 -0.1  3. ]
 [ 0.  -3.   6.5]]


Becuase, numpy module has large number of functions whose names conflict with built-in Python functions (like min and max). 

In [28]:
data.shape # shape is object in numpy used to check dimension of array. 

(2, 3)

In [27]:
data.dtype  # dtype, an object in numpy describing the data type of the array

dtype('float64')

## Creating ndarrays

The easiest way to create an array is to use the array function. This accepts any sequence-like object and produces a new NumPy array containing the passed data. 

It is good for conversion.

In [1]:
data1 = [6, 7.5, 8, 0, 1]

In [3]:
import numpy as np
arr1 = np.array(data1)

In [4]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

Nested sequences, like a list of equal length lists, will be converted into a multidimensional array:

In [5]:
data2 = [[1, 2, 3, 4],[5,6,7,8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

Since data2 was a list of lists. the NumPy arrays arr2 has two dimensions, with shape inferred from the data. we can confirm this by inspecting the ndim and shape attribures:

In [6]:
arr2.ndim

2

In [8]:
arr2.shape

(2, 4)

In [9]:
arr2.dtype

dtype('int32')

In [11]:
arr1.dtype

dtype('float64')

In addition to numpy.array there are a number of other functions for creating new arrays. As examples numpy.zeros and numpy.ones create arrays of 0s or 1s, respectively, with a given length or shape. numpy.empty creates an array without initializing its values to any particular value. 

To create a higher dimensional array with these methods, pass a tuple for the shape

In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [15]:
np.empty((2,3,2))

array([[[9.57613755e-312, 2.47032823e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.11260619e-306, 5.74084271e+169]],

       [[6.86772608e-091, 1.31397834e-047],
        [8.25997790e-072, 1.04000717e-042],
        [3.99910963e+252, 3.11023271e+179]]])

numpy.arange is an array values version of built in Python range function

In [17]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

NumPy is focused on numerical computing. the data type if not specified , will in many cases be float64

- array          : Convert input data to an ndarray either by inferring a data type or explicity specifing a data type; copies the input data by default
- asarray        : Convert input to ndarray, but do not copy the input is already an ndarray
- arange         : Like the built in range but return an ndarray instead of a list.
- ones           : Produces an array all of 1s
- ones_like      : produces an array of the same shape and data type.
- zeros          : like onesand ones_like but producing arrays of 0s instead.
- empty          : Create new array by allocating new memory, but do not populate with any valeus like ones and zeros
- empty_like     : zeros
- full           ; produces an array of the given shape and data type with all values set to indicated "fill value"
- eye, identity  : create a square N x N identity matrix (1s on the diagonal and 0s else where)

## Data Types of ndarrays

The *data type* or dtype is a special object containing the information the ndarray needs to interpret a chunk of memory as a particular type of data

In [19]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)

arr1.dtype


dtype('float64')

In [20]:
arr2.dtype

dtype('int32')

To know more about NumPy data types, please visit 

https://numpy.org/devdocs/reference/arrays.dtypes.html#arrays-dtypes

you can convert or cast an array from one data type to another using ndarray's astype method

In [23]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype    # if you are getting int32 its because of you 32-bit system or you might installed Python 32-bit version. 

dtype('int32')

In [24]:
### to check your system version 
import platform
print(platform.architecture())

('64bit', 'WindowsPE')


In [29]:
float_arr = arr.astype(np.float64)
float_arr


array([1., 2., 3., 4., 5.])

In [31]:
float_arr.dtype

dtype('float64')

In this example, integers were cast to floating point. If i cast floating-point numbers to be of integers data type, the decimal part will be truncated.

In [32]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [33]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

If you have an array of strings representing numbers, you can use astype to convert them to numeric form

In [35]:
numeric_strings = np.array(["1.25", "-9.6", "42"], dtype=np.string_)
numeric_strings.dtype

dtype('S4')

In [37]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

There are shorthand type code strings you can use to refer to a dtype

In [39]:
zeros_uint32 = np.zeros(8, dtype="u4")
zeros_uint32

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint32)

In [40]:
### Calling as type always creates a new array ( a cpy of the data), even itf the new data type is the same as the old data type.

## Arithmetic with NumPy Arrays

Arrays are important becuase they enable you to express batch operations on data without writing any for loops. NumPy users call this ***vectorization***. Any arithmetic operations between equal-size arrays apply with operations element wise

In [5]:
import numpy as np
arr = np.array([[1., 2., 3.,], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [6]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [7]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

Arithmetic operations with scalar propagate the scalar argument to each element in the array:

In [8]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [9]:
arr ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

Comparision operators between arrays of the same size yield boolean arrays:

In [10]:
arr2 = np.array([
    [0., 4., 1.],
    [7., 2., 12.]
])
arr2 

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [11]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

Evaluating operation between differently sized arrays is called ***broadcasting***.

## Basic indexing and Slicing

In [13]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr[5]

5

In [16]:
arr[5:8]

array([5, 6, 7])

In [18]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [19]:
## Slicing

arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [25]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    64, 12345,    64,     8,
           9])

The "bare" slice [:] will assign all values in array:

In [26]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

If you are new to NumPy, you might be surprised by this, especially if you have used other array programming languages that copy data more eagerly. As NumPy has been designed to be able to work with very large arrays, you could imagine performance and memory problems if NumPy insisted on always copying data.


With higher dimensional arrays, you have many more options. In a two-dimensional array, the elements at each index are no longer scalars but rather one-dimensional arrays:

In [27]:
arr2d = np.array([
    [1, 2, 3],[4, 5, 6],[7, 8, 9]
])
arr2d[2]

array([7, 8, 9])

Thus, individual elements can be accessed recursively. But that is a bit too much work, so you can pass a comma-separated list of indices to select individual elements.So these are equivalent:


In [28]:
arr2d[0][2]

3

In [29]:
arr2d[0, 2]

3

In multidimensional arrays, if you omit later indices, the returned object will be a lower dimensional ndarray consisting of all the data along the higher dimensions. So in the 2 × 2 × 3 array arr3d:

In [42]:
arr3d = np.array([
    [
        [1, 2, 3], [4, 5, 6]
    ],
    [
        [7, 8, 9], [10, 11, 12]
    ]
])  ### simpy you can alsow write. [[[1, 2, 3], [4, 5, 6]],[[7, 8,9,], [10, 11, 12]]]

arr3d 

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [43]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

Both scalar values and arrays can be assigned to arr3d[0]:

In [45]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [46]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

Similary, arr3d[1, 0] gives you all the values whose indices start with (1, 0), forming a one-dimensional array:

In [47]:
arr3d[1, 0]

array([7, 8, 9])

This expression is same as though we have indexed in two steps:

In [56]:
x = arr3d[1]
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [57]:
x[0]

array([7, 8, 9])