NUMPY

Numpy is a fundamental libray for scientific computing in Python. It porivdes support for arrays
and matrices, along with a collection of mathematical functions to operate on these data structures.

In [2]:
import numpy as np #np is just alias 

## creating array  using nump

## creating a 1D array

arr1 = np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [ ]:
print(type(arr1))  # type of array

<class 'numpy.ndarray'>


In [7]:
print(arr1.shape) # shape of array

(5,)


In [10]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)               

array([[1, 2, 3, 4, 5]])

In [12]:
arr2 = np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [15]:
arr3 = np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(arr3)
print(arr3.shape)

[[1 2 3 4 5]
 [1 2 3 4 5]]
(2, 5)


In [21]:
c = np.arange(0,10,2)

print("\n")

print(c.reshape(5,1)) #reshaping single dim array to 2D array



[[0]
 [2]
 [4]
 [6]
 [8]]


In [23]:
np.ones((3,4))  #3 rows and 4 columns

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
## idnetity matrix

np.eye(3)   #diagnoal elements make same

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
arr = np.array([[1,2,3,4],[5,6,7,8]])

print("Array:\n", arr)
print("Shape:", arr.shape) # ouput 2,3
print("Number of dimensions:", arr.ndim) # output: 2
print("Size (number of elements):",arr.size) # output 8
print("Data Type:", arr.dtype) # output int64 
print("Item size : ", arr.itemsize)  # varies based on platform

Array:
 [[1 2 3 4]
 [5 6 7 8]]
Shape: (2, 4)
Number of dimensions: 2
Size (number of elements): 8
Data Type: int64
Item size :  8


In [ ]:
## Numpy vectorized operation
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

## Element wise amathematial operations
print("Add :", arr1 + arr2)
print("Sub: ", arr1-arr2)

Add : [11 22 33 44 55]
Sub:  [ -9 -18 -27 -36 -45]


In [33]:
## Universal functions
arr4 = np.array([2,3,4,5,6])

## square root
print(np.sqrt(arr4))
print("\n")

## Exponential
print(np.exp(arr))
print("\n")

## Sin
print(np.sin(arr))
print("\n")

## natural log
print(np.log)

[1.41421356 1.73205081 2.         2.23606798 2.44948974]


[[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01]
 [1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03]]


[[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
 [-0.95892427 -0.2794155   0.6569866   0.98935825]]


<ufunc 'log'>


In [37]:
## arrary slicing and indexing

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array : \n", arr)

Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [39]:
arr[0]  

array([1, 2, 3, 4])

In [47]:
arr[2][3]   #2 is for row and #3 is col indexing

np.int64(12)

In [49]:
arr[2:]  # starting from 2 row and till end

array([[ 9, 10, 11, 12]])

In [51]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [60]:
print(arr[0:2,2:])

[[3 4]
 [7 8]]


In [62]:
# Modiy array elements

arr[0,0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [65]:
arr[1:] = 100

print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [68]:
## statistical concepts -- normalization
## to have a mean of 0 and standard deviation of 1
data = np.array([1,2,3,4,5])

## Calcuate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

## normalize the data
normalized_data = (data - mean)/std_dev
print("Normalized data : ", normalized_data)



Normalized data :  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [70]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

## Mean
mean = np.mean(data)
print("Mean : ", mean)

## Median
median = np.median(data)
print("Median : ", median) 

## Standard deviation
std_dev = np.std(data)
print("Standard Deviation", std_dev)

## Variance
variance = np.var(data)
print("Varaince: ", variance)

Mean :  5.5
Median :  5.5
Standard Deviation 2.8722813232690143
Varaince:  8.25


In [74]:
## Logical Operation
data = np.array([1,2,3,4,5,6,7,8,9,10])

data[(data >= 5) & (data <= 8)]

array([5, 6, 7, 8])