# Universal Functions: Fast Element-Wise Array Functions

A universal function, or ufunc, is a function that performs element-wise operations on data in ndarrays. You can think of them as fast vectorized wrappers for simple functions that take one or more scalar values and produce one or more scalar results.

Many ufuncs are simple element-wise transformations, like numpy.sqrt or numpy.exp:

In [1]:
import numpy as np

In [5]:
arr = np.arange(10)

In [6]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [8]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

These are referred to as unary ufuncs. Others, such as numpy.add or numpy.maximum, take two arrays (thus, binary ufuncs) and return a single array as the result:


In [11]:
rng = np.random.default_rng(seed=12345)

data = rng.standard_normal((2,3))

x = rng.standard_normal(8)

y = rng.standard_normal(8)

In [12]:
x

array([-1.3677927 ,  0.6488928 ,  0.36105811, -1.95286306,  2.34740965,
        0.96849691, -0.75938718,  0.90219827])

In [13]:
y

array([-0.46695317, -0.06068952,  0.78884434, -1.25666813,  0.57585751,
        1.39897899,  1.32229806, -0.29969852])

In [14]:
np.maximum(x, y)

array([-0.46695317,  0.6488928 ,  0.78884434, -1.25666813,  2.34740965,
        1.39897899,  1.32229806,  0.90219827])

In this example, numpy.maximum computed the element-wise maximum of the elements in x and y

While not common, a ufunc can return multiple arrays. numpy.modf is one example:
a vectorized version of the built-in Python math.modf, it returns the fractional and integral parts of a floating-point array:


In [15]:
arr = rng.standard_normal(7) * 5

arr

array([ 4.51459671, -8.10791367, -0.7909463 ,  2.24741966, -6.71800536,
       -0.40843795,  8.62369966])

In [17]:
remainder, whole_part = np.modf(arr)

In [18]:
remainder

array([ 0.51459671, -0.10791367, -0.7909463 ,  0.24741966, -0.71800536,
       -0.40843795,  0.62369966])

In [19]:
whole_part

array([ 4., -8., -0.,  2., -6., -0.,  8.])

Ufuncs accept an optional out argument that allows them to assign their results into an existing array rather than create a new one:


In [20]:
arr

array([ 4.51459671, -8.10791367, -0.7909463 ,  2.24741966, -6.71800536,
       -0.40843795,  8.62369966])

In [21]:
out = np.zeros_like(arr)

In [22]:
np.add(arr, 1)

array([ 5.51459671, -7.10791367,  0.2090537 ,  3.24741966, -5.71800536,
        0.59156205,  9.62369966])

In [23]:
np.add(arr, 1, out=out)

array([ 5.51459671, -7.10791367,  0.2090537 ,  3.24741966, -5.71800536,
        0.59156205,  9.62369966])

In [24]:
arr

array([ 4.51459671, -8.10791367, -0.7909463 ,  2.24741966, -6.71800536,
       -0.40843795,  8.62369966])

In [25]:
out

array([ 5.51459671, -7.10791367,  0.2090537 ,  3.24741966, -5.71800536,
        0.59156205,  9.62369966])

for a listing of some of NumPy’s ufuncs. New ufuncs continue to be added to NumPy, so consulting the online NumPy documentation is the best way to get a comprehensive listing and stay up to date.

> some unary universal functions as below

| Function(s)                             | Description                                                                                          |
|----------------------------------------|------------------------------------------------------------------------------------------------------|
| `abs`, `fabs`                          | Compute the absolute value element-wise for integer, float, or complex values                        |
| `sqrt`                                 | Compute the square root of each element (`arr ** 0.5`)                                               |
| `square`                               | Compute the square of each element (`arr ** 2`)                                                      |
| `exp`                                  | Compute the exponent `e^x` of each element                                                           |
| `log`, `log10`, `log2`, `log1p`        | Natural log (base `e`), log base 10, log base 2, and `log(1 + x)`, respectively                      |
| `sign`                                 | Compute the sign of each element: `1` (positive), `0` (zero), `-1` (negative)                        |
| `ceil`                                 | Compute the ceiling (smallest integer ≥ element)                                                     |
| `floor`                                | Compute the floor (largest integer ≤ element)                                                        |
| `rint`                                 | Round elements to the nearest integer, preserving the data type                                      |
| `modf`                                 | Return fractional and integral parts as separate arrays                                              |
| `isnan`                                | Return Boolean array indicating if each value is NaN                                                 |
| `isfinite`, `isinf`                    | Return Boolean arrays: is finite (`not inf or NaN`) or is infinite                                   |
| `cos`, `cosh`, `sin`, `sinh`, `tan`, `tanh` | Regular and hyperbolic trigonometric functions                                                   |
| `arccos`, `arccosh`, `arcsin`, `arcsinh`, `arctan`, `arctanh` | Inverse trigonometric functions                                            |
| `logical_not`                          | Compute truth value of `not x` element-wise (equivalent to `~arr`)                                   |

> some binary universal fuctions as below

| Function(s)                                                         | Description                                                                                       |
|--------------------------------------------------------------------|---------------------------------------------------------------------------------------------------|
| `add`                                                              | Add corresponding elements in arrays                                                              |
| `subtract`                                                         | Subtract elements in second array from first array                                                |
| `multiply`                                                         | Multiply array elements                                                                           |
| `divide`, `floor_divide`                                           | Divide or floor divide (truncating the remainder)                                                 |
| `power`                                                            | Raise elements in first array to powers indicated in second array                                 |
| `maximum`, `fmax`                                                  | Element-wise maximum; `fmax` ignores NaN                                                          |
| `minimum`, `fmin`                                                  | Element-wise minimum; `fmin` ignores NaN                                                          |
| `mod`                                                              | Element-wise modulus (remainder of division)                                                      |
| `copysign`                                                         | Copy sign of values in second argument to values in first argument                                |
| `greater`, `greater_equal`, `less`, `less_equal`, `equal`, `not_equal` | Element-wise comparison; returns Boolean arrays (`>`, `>=`, `<`, `<=`, `==`, `!=`)          |
| `logical_and`                                                      | Element-wise truth value of AND (`&`) logical operation                                           |
| `logical_or`                                                       | Element-wise truth value of OR (`|`) logical operation                                            |
| `logical_xor`                                                      | Element-wise truth value of XOR (`^`) logical operation                                           |
