# Linear Algebra

Linear algebra operations, like matrix multiplication, decompositions, determinants,
and other square matrix math, are an important part of many array libraries. Multi‐
plying two two-dimensional arrays with * is an element-wise product, while matrix
multiplications require using a function. Thus, there is a function dot, both an array
method and a function in the numpy namespace, for matrix multiplication:

In [1]:
import numpy as np

x = np.array([[1., 2., 3.], [4., 5., 6.]])

y = np.array([[6., 23.], [-1, 7], [8, 9]])

x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [2]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [4]:
x.dot(y)  #x.dot(y) is euivalent to np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [5]:
np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

A matrix product between a two-dimensional array and a suitably sized onedimensional array results in a one-dimensional array:


In [6]:
x @ np.ones(3)

array([ 6., 15.])

numpy.linalg has a standard set of matrix decompositions and things like inverse
and determinant:

In [9]:
from numpy.linalg import inv, qr

rng = np.random.default_rng(seed=12345)
X = rng.standard_normal((5, 5))

mat = X.T @ X

inv(mat)

array([[ 0.15548538, -0.36723081, -0.52638547, -0.2300642 , -0.04646089],
       [-0.36723081,  2.54917814,  3.47827334,  1.48196722,  0.22206454],
       [-0.52638547,  3.47827334,  5.46389554,  2.46214396,  0.63467543],
       [-0.2300642 ,  1.48196722,  2.46214396,  1.38302896,  0.33430132],
       [-0.04646089,  0.22206454,  0.63467543,  0.33430132,  0.33879566]])

In [10]:
mat @ inv(mat)

array([[ 1.00000000e+00,  4.99285027e-17, -2.32472626e-16,
        -2.35388056e-16, -1.12575057e-18],
       [ 1.55867966e-16,  1.00000000e+00,  9.98311990e-17,
        -1.96348091e-16, -3.86511231e-16],
       [-6.92418622e-17, -7.91606813e-16,  1.00000000e+00,
         5.64803789e-16,  1.61057761e-16],
       [-2.37101845e-16,  1.84817406e-15,  3.81257497e-15,
         1.00000000e+00,  3.71349003e-16],
       [ 9.72642079e-17,  2.31009855e-16, -7.19939179e-17,
        -4.80724193e-16,  1.00000000e+00]])

### 📐 NumPy Linear Algebra (`numpy.linalg`) Functions

| Function      | Description                                                                                      |
|---------------|--------------------------------------------------------------------------------------------------|
| `diag`        | Return the diagonal (or off-diagonal) elements of a square matrix as a 1D array, or convert a 1D array into a square matrix with zeros on the off-diagonal |
| `dot`         | Perform matrix multiplication                                                                     |
| `trace`       | Compute the sum of the diagonal elements of a matrix                                              |
| `det`         | Compute the determinant of a matrix                                                               |
| `eig`         | Compute the eigenvalues and eigenvectors of a square matrix                                       |
| `inv`         | Compute the inverse of a square matrix                                                            |
| `pinv`        | Compute the Moore-Penrose pseudoinverse of a matrix                                               |
| `qr`          | Compute the QR decomposition of a matrix                                                          |
| `svd`         | Compute the singular value decomposition (SVD) of a matrix                                        |
| `solve`       | Solve the linear system Ax = b for x, where A is a square matrix                                  |
| `lstsq`       | Compute the least-squares solution to Ax = b                                                      |
